### ISSUE TITLE
GitLab boards with shared columns

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/ProjectTemplate#9]
Now I have a new concern... if GitLab puts a card into a column by label, and if all issues are automatically on all boards, then if a team add a "doing" label to their card, would it move to the "doing" column on all teams' boards? If this is the case we would need to create a set of labels for each team (e.g., "t1 to do", "t1 doing", "t2 to do", "t2 doing", ...). That means setup is more complicated.

Trying to answer my own question I read this https://docs.gitlab.com/ee/user/project/issue_board.html#advanced-team-handover . This suggests that boards with common columns can be used to hand-off between teams. In their example, both teams have a "Frontend" column. This is used to hand-off an issue from a UX team to a Frontend team. I'm assuming this works because they both have a column named "Frontend". The trouble I'm having is that in the same example both teams have a "Doing" column. If the UX team, say, moved a card to "Doing" wouldn't it also show up on the Frontend team's board? Or is there some more magic to prevent that?

**Comment by cradkowski** [comment]
@StoneyJackson 
I replicated the board setup they were using in the example from https://docs.gitlab.com/ee/user/project/issue_board.html#advanced-team-handover

I created both of the boards under the same repository so they are at the same level.
You are correct, if both boards at the same level have a "Doing" column (from a project label) then a card moved on one board is automatically moved on the other and the labels change. This is also how it works with the hand-off for the "Frontend" column that they are talking about.

I think this may have been a bad example on GitLab's part as it doesn't seem like you can have the same label or column name on boards at the same level of a repository and have them be separate. 

To avoid this with boards at the same level you would need to add something like "Team1 Doing" as you cannot have multiple labels with the same name.

**Comment by StoneyJackson** [comment]
Good to know.

This could get messy if there are lots of teams. Now I'm starting to like the one-board-with-filters model. Then each shop and/or team would need a label (this would need to be part of setup). Then folks filter based on shop or team.

This is interesting. It means that boards should be associated with specific workflows with specific labels, rather than per team.

Another thought... Can a board have a filter applied for all viewers (or a default filter)? If so, we could still create multiple boards with the same columns but with a default filter based on the team or shop the board is for.

In any case we have to make a we'll defined list of workflow labels. I brainstormed a list somewhere in docs/dev . (I'd give you a link but I'd be fighting my phone)

**Comment by StoneyJackson** [comment]
Closing because my question has been answered.
